apiVersion: v1
data:
  config.yaml: |-
    debugmode: {{ .Values.debugMode }}
    port: {{ .Values.config.serverPort }}
    metrics:
      probes:{{- range .Values.config.metricsProbes }}
      - {{ . }}{{- end }}
    events:
      probes: {{- range .Values.config.eventProbes }}
      - {{ . }}{{- end }}
      sinks: {{- range .Values.config.eventSinks }}
      - {{ . }}{{- end }}
kind: ConfigMap
metadata:
  name: kubeskoop-config
  namespace: {{ .Release.Namespace }}
