debugmode: false
metric_config:
  interval: 15
  port: 9102
  probes:
  - netdev
  - io
  - sock
  - tcpsummary
  - tcp
  - tcpext
  - udp
  - flow
event_config:
  port: 19102
  loki_enable: false
  loki_address: loki-service
