debugmode: true
port: 10080
metrics:
  probes:
  - name: conntrack
  - name: qdisc
  - name: netdev
  - name: io
  - name: sock
  - name: tcpsummary
  - name: tcp
  - name: tcpext
  - name: udp
  - name: kernellatency
  - name: packetloss
event:
  probes:
  - name: biolatency
  - name: kernellatency
  - name: packetloss
  - name: tcpreset
  sinks:
  - name: stderr
  - name: file
    args:
      path: /tmp/exporter.json

