debugMode: true
port: 9102
enableController: true
metrics:
  probes:
  - name: conntrack
  - name: qdisc
  - name: netdev
  - name: io
  - name: sock
  - name: tcpsummary
  - name: tcp
  - name: tcpext
  - name: udp
  - name: kernellatency
  - name: packetloss
    args:
      enableStack: false
  - name: flow
    args:
      enablePortInLabel: false
  - name: tcpretrans
event:
  probes: 
  - name: biolatency
  - name: kernellatency
  - name: packetloss
    args:
      enableStack: false
  - name: tcpreset
  - name: tcpretrans
  sinks: 
  - name: stderr

