name: kubeskoop-exporter
debugMode: false
runtimeEndpoint: /run/containerd/containerd.sock
appName: kubeskoop-exporter

image:
  repository: kubeskoop/kubeskoop
  # Overrides the image tag whose default is the chart appVersion.
  tag: v0.1.1
  imagePullPolicy: IfNotPresent

initContainer:
  enabled: true
  repository: kubeskoop/btfhack
  tag: v0.1.1
  imagePullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 1024Mi

config:
  serverPort: 9102
  metricsProbes:
    - name: netdev
    - name: io
    - name: socketlatency
    - name: packetloss
    - name: net_softirq
    - name: tcpext
    - name: tcpsummary
    - name: tcp
    - name: sock
    - name: softnet
    - name: udp
    - name: virtcmdlatency
    - name: kernellatency
  eventProbes:
    - name: tcpreset
    - name: packetloss
  eventSinks:
    - name: stderr

nodeSelector: { }
tolerations: { }
